create table if not exists crmgenesis_slot(
    ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STATUS_ID INT (18) UNSIGNED NOT NULL,
    DATE_FROM DATETIME NULL,
    DATE_TO DATETIME NULL,
    TYPE_ID INT (18) UNSIGNED NOT NULL,
    CLUB_ID INT (18) UNSIGNED NOT NULL,
    ZONE_ID INT (18) UNSIGNED NOT NULL,
    LOCATION_ID INT (18) UNSIGNED NOT NULL,
    AGE_FROM INT (18) UNSIGNED NULL,
    AGE_TO INT (18) UNSIGNED NULL,
    GROUP_SIZE INT (18) UNSIGNED NULL,
    GROUP_NAME VARCHAR (255),
    USER_ID INT (18) UNSIGNED NOT NULL,
    DATE_CREATE DATETIME NULL,
    DATE_MODIFY DATETIME NULL,
    CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
    SERVICE_ID INT (18) UNSIGNED NOT NULL
);

create table if not exists crmgenesis_slot_business(
    ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OWNER_ID INT (18) UNSIGNED NOT NULL,
    STATUS_ID INT (18) UNSIGNED NOT NULL,
    DATE_FROM DATETIME NULL,
    DATE_TO DATETIME NULL,
    DATE_CREATE DATETIME NULL,
    DATE_MODIFY DATETIME NULL,
    CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
    CLIENT_ID INT (18) UNSIGNED NOT NULL,
    TYPE_ID INT (18) UNSIGNED NOT NULL
);
