create table if not exists crmgenesis_slots(
    ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATE_FROM DATETIME NULL,
    DATE_TO DATETIME NULL,
    STATUS_ID INT (18) UNSIGNED NOT NULL,
    SERVICE_ID INT (18) UNSIGNED NOT NULL,
    LOCATION_ID INT (18) UNSIGNED NOT NULL,
    USER_ID INT (18) UNSIGNED NOT NULL,
    AGE_FROM INT (18) UNSIGNED NULL,
    AGE_TO INT (18) UNSIGNED NULL,
    DATE_CREATE DATETIME NULL,
    DATE_MODIFY DATETIME NULL,
    CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL
);

create table if not exists crmgenesis_slot_business(
    ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID INT (18) UNSIGNED NOT NULL,
    TYPE_ID INT (18) UNSIGNED NOT NULL,
    STATUS INT (18) UNSIGNED NOT NULL,
    DATE_CREATE DATETIME NULL,
    DATE_MODIFY DATETIME NULL,
    CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL
);
